package web

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"image"
	"image/png"
	"m365-copilot2api/internal/auth"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

func TestChatImagesReachExternalClientProtocols(t *testing.T) {
	var data bytes.Buffer
	if err := png.Encode(&data, image.NewRGBA(image.Rect(0, 0, 2, 2))); err != nil {
		t.Fatal(err)
	}
	source := "data:image/png;base64," + base64.StdEncoding.EncodeToString(data.Bytes())
	s := &Server{}
	r := httptest.NewRequest("POST", "https://nas.example/v1/chat/completions", nil)
	urls, err := s.hostChatImages(r.Context(), r, []string{source, source}, auth.AccountToken{})
	if err != nil || len(urls) != 1 {
		t.Fatalf("deduped URLs=%v err=%v", urls, err)
	}
	rr := httptest.NewRecorder()
	s.generatedImageFile(rr, httptest.NewRequest("GET", urls[0], nil))
	if rr.Code != http.StatusOK || !bytes.Equal(rr.Body.Bytes(), data.Bytes()) {
		t.Fatal("anonymous image download did not match generated bytes")
	}
	md := "![image](" + urls[0] + ")"
	for _, stream := range []bool{false, true} {
		out := httptest.NewRecorder()
		s.writeChatCompletionText(out, r, "gpt-image-2", md, stream, true, 1)
		if !strings.Contains(out.Body.String(), urls[0]) {
			t.Fatal("OpenAI output lost image URL")
		}
	}
	out := httptest.NewRecorder()
	s.writeChatCompletionText(out, r, "gpt-image-2", md, false, true, 1)
	var payload map[string]any
	if err := json.Unmarshal(out.Body.Bytes(), &payload); err != nil {
		t.Fatal(err)
	}
	for _, stream := range []bool{false, true} {
		converted := httptest.NewRecorder()
		writeAnthropicResult(converted, "gpt-image-2", stream, payload)
		if !strings.Contains(converted.Body.String(), urls[0]) {
			t.Fatal("Anthropic output lost image URL")
		}
	}
}

func TestChatImagesRejectFalseSuccess(t *testing.T) {
	s := &Server{}
	r := httptest.NewRequest("POST", "http://nas/v1/chat/completions", nil)
	for _, sources := range [][]string{nil, {"data:image/png;base64," + base64.StdEncoding.EncodeToString([]byte("not an image"))}, {"https://example.org/image.png"}, {"data:image/png"}} {
		if urls, err := s.hostChatImages(r.Context(), r, sources, auth.AccountToken{}); err == nil || len(urls) != 0 {
			t.Fatalf("false success: %v %v", urls, err)
		}
	}
	ctx, cancel := context.WithCancel(r.Context())
	cancel()
	if _, err := s.hostChatImages(ctx, r, []string{"data:image/png;base64,AA=="}, auth.AccountToken{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("cancellation lost: %v", err)
	}
}

func TestWriteChatCompletionTextNonStreamingUsage(t *testing.T) {
	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
	server := &Server{}
	server.writeChatCompletionText(rr, req, "gpt-5.6-sol", "![image](http://example/image.png)", false, true, 17)

	var out map[string]any
	if err := json.Unmarshal(rr.Body.Bytes(), &out); err != nil {
		t.Fatal(err)
	}
	usage := out["usage"].(map[string]any)
	if got := int64(usage["prompt_tokens"].(float64)); got != 17 {
		t.Fatalf("prompt_tokens=%d want 17", got)
	}
	choices := out["choices"].([]any)
	content := choices[0].(map[string]any)["message"].(map[string]any)["content"].(string)
	if !strings.Contains(content, "![image]") {
		t.Fatalf("image markdown missing: %q", content)
	}
}

func TestRequestContextEnded(t *testing.T) {
	req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
	if requestContextEnded(req, nil) {
		t.Fatal("live request was classified as ended")
	}
	ctx, cancel := context.WithCancel(req.Context())
	cancel()
	if !requestContextEnded(req.WithContext(ctx), nil) {
		t.Fatal("canceled request context was not detected")
	}
}

func TestChatImageRouteTimeouts(t *testing.T) {
	for _, tc := range []struct {
		seconds int
		total   time.Duration
		attempt time.Duration
	}{
		{seconds: 2, total: 5 * time.Second, attempt: 5 * time.Second},
		{seconds: 120, total: 2 * time.Minute, attempt: 2 * time.Minute},
		{seconds: 300, total: 5 * time.Minute, attempt: 3 * time.Minute},
		{seconds: 3600, total: 10 * time.Minute, attempt: 3 * time.Minute},
	} {
		total, attempt := chatImageRouteTimeouts(tc.seconds)
		if total != tc.total || attempt != tc.attempt {
			t.Fatalf("seconds=%d got (%s,%s), want (%s,%s)", tc.seconds, total, attempt, tc.total, tc.attempt)
		}
	}
}

func TestChatImageKeepaliveAndStreamingErrorStaySSECompatible(t *testing.T) {
	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
	stop, ok := startChatImageKeepalive(rr, req)
	if !ok {
		t.Fatal("httptest recorder should support flushing")
	}
	stop()
	writeChatImageRouteError(rr, true, errors.New("no image returned"))
	body := rr.Body.String()
	for _, want := range []string{": image generation started", `"type":"image_generation_error"`, "data: [DONE]"} {
		if !strings.Contains(body, want) {
			t.Fatalf("SSE route response missing %q: %s", want, body)
		}
	}
}

func TestWriteChatCompletionTextStreamingUsageOption(t *testing.T) {
	for _, tc := range []struct {
		name      string
		sendUsage bool
		wantUsage bool
	}{
		{name: "disabled", sendUsage: false, wantUsage: false},
		{name: "enabled", sendUsage: true, wantUsage: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rr := httptest.NewRecorder()
			req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
			server := &Server{}
			server.writeChatCompletionText(rr, req, "gpt-5.6-sol", "![image](http://example/image.png)", true, tc.sendUsage, 23)
			body := rr.Body.String()
			if !strings.Contains(body, "data: [DONE]") || !strings.Contains(body, `"finish_reason":"stop"`) {
				t.Fatalf("invalid SSE completion: %s", body)
			}
			if got := strings.Contains(body, `"usage":`); got != tc.wantUsage {
				t.Fatalf("usage present=%v want %v: %s", got, tc.wantUsage, body)
			}
		})
	}
}
