package web

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"image"
	"image/png"
	"m365-copilot2api/internal/auth"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

func TestChatImagesReachExternalClientProtocols(t *testing.T) {
	t.Setenv("M365_DATA_DIR", t.TempDir())
	var data bytes.Buffer
	if err := png.Encode(&data, image.NewRGBA(image.Rect(0, 0, 2, 2))); err != nil {
		t.Fatal(err)
	}
	source := "data:image/png;base64," + base64.StdEncoding.EncodeToString(data.Bytes())
	s := &Server{}
	r := httptest.NewRequest("POST", "https://nas.example/v1/chat/completions", nil)
	imgs, err := s.hostChatImages(r.Context(), r, []string{source, source}, auth.AccountToken{})
	if err != nil || len(imgs) != 1 {
		t.Fatalf("deduped images=%v err=%v", imgs, err)
	}
	rr := httptest.NewRecorder()
	s.generatedImageFile(rr, httptest.NewRequest("GET", imgs[0].URL, nil))
	if rr.Code != http.StatusOK || !bytes.Equal(rr.Body.Bytes(), data.Bytes()) {
		t.Fatal("anonymous image download did not match generated bytes")
	}

	// The inline form has to carry exactly the bytes the hosted copy serves, or a
	// client that renders the inline image and a client that opens the link would
	// show different pictures.
	meta, payload64, ok := strings.Cut(imgs[0].DataURL, ",")
	if !ok || !strings.HasPrefix(meta, "data:image/") || !strings.HasSuffix(meta, ";base64") {
		t.Fatalf("inline form is not a base64 image data URL: %q", meta)
	}
	inline, err := base64.StdEncoding.DecodeString(payload64)
	if err != nil {
		t.Fatalf("inline payload is not base64: %v", err)
	}
	if !bytes.Equal(inline, rr.Body.Bytes()) {
		t.Fatal("inline image and hosted copy are different bytes")
	}

	// Render through the production renderer, then push the result through both
	// response writers: every client protocol must receive the picture itself.
	md := chatImageBlocks("prompt", imgs)
	for _, stream := range []bool{false, true} {
		out := httptest.NewRecorder()
		s.writeChatCompletionText(out, r, "gpt-image-2", md, stream, true, 1)
		body := out.Body.String()
		if !strings.Contains(body, imgs[0].DataURL) {
			t.Fatal("OpenAI output did not carry the inline image")
		}
		if !strings.Contains(body, imgs[0].URL) {
			t.Fatal("OpenAI output lost the download URL")
		}
	}
	out := httptest.NewRecorder()
	s.writeChatCompletionText(out, r, "gpt-image-2", md, false, true, 1)
	var payload map[string]any
	if err := json.Unmarshal(out.Body.Bytes(), &payload); err != nil {
		t.Fatal(err)
	}
	for _, stream := range []bool{false, true} {
		converted := httptest.NewRecorder()
		writeAnthropicResult(converted, "gpt-image-2", stream, payload)
		body := converted.Body.String()
		if !strings.Contains(body, imgs[0].DataURL) {
			t.Fatal("Anthropic output did not carry the inline image")
		}
		if !strings.Contains(body, imgs[0].URL) {
			t.Fatal("Anthropic output lost the download URL")
		}
	}
}

// The client-facing shape for a generated image is decided in one place. It has
// to hand over the picture itself: a client given only a URL must fetch it back
// from the gateway, which fails when the derived public address is unreachable,
// and the user then sees a link instead of an image.
func TestChatImageBlocksEmbedTheImageAndKeepADownloadLink(t *testing.T) {
	imgs := []hostedChatImage{
		{DataURL: "data:image/png;base64,AAAA", URL: "https://nas.example/v1/images/1.png"},
		{DataURL: "data:image/jpeg;base64,BBBB", URL: "/v1/images/2.jpg"},
	}
	got := chatImageBlocks("a cat", imgs)

	for _, im := range imgs {
		if !strings.Contains(got, "]("+im.DataURL+")") {
			t.Fatalf("inline image missing for %s://n%s", im.URL, got)
		}
		if !strings.Contains(got, "[下载图片]("+im.URL+")") {
			t.Fatalf("download link missing for %s://n%s", im.URL, got)
		}
	}
	if strings.Count(got, "![") != 2 {
		t.Fatalf("expected one image per generated result://n%s", got)
	}
	// A relative URL is fine - the web console serves one - but nothing may be
	// rendered as the image source except the inline bytes.
	if strings.Contains(got, "![a cat](https://nas.example") {
		t.Fatalf("the remote URL leaked into the image source://n%s", got)
	}
}

// The alt text comes from the user's prompt, so it must not be able to break out
// of the Markdown image and inject a second element - that would hide the picture
// the caller asked for.
func TestChatImageBlocksSanitizeAltText(t *testing.T) {
	got := chatImageBlocks("cat](https://evil.example/x.png)![y\nsecond line", []hostedChatImage{
		{DataURL: "data:image/png;base64,AAAA", URL: "/v1/images/1.png"},
	})
	if n := strings.Count(got, "!["); n != 1 {
		t.Fatalf("alt text opened %d images, want 1:\n%s", n, got)
	}
	if n := strings.Count(got, "]("); n != 2 {
		// Exactly two: the image source and the download link.
		t.Fatalf("alt text introduced %d link targets, want 2:\n%s", n, got)
	}
	if strings.Contains(got, "evil.example/x.png)") {
		t.Fatalf("alt text closed the image and injected a link://n%s", got)
	}
	if !strings.Contains(got, "](data:image/png;base64,AAAA)") {
		t.Fatalf("inline image was damaged by the alt text://n%s", got)
	}
	if strings.Contains(got, "\nsecond line") {
		t.Fatalf("a newline survived in the alt, which would end the image line://n%s", got)
	}
}

func TestAnthropicImagePromptWithSystemReminderRoutesOnOrdinaryModel(t *testing.T) {
	req := anthropicRequest{
		Model: "gpt-5.6-sol",
		Messages: []anthropicMessage{{
			Role: "user",
			Content: []any{map[string]any{
				"type": "text",
				"text": "按以下提示词生成图片：东方仙侠男主电影级海报，8K，竖版。" +
					"<system-reminder>You are a coding agent. Use tools and save the PNG under /mnt/data.</system-reminder>",
			}},
		}},
	}
	o, err := req.openAI()
	if err != nil {
		t.Fatal(err)
	}
	if got := lastMessageRole(o.Messages); got != "user" {
		t.Fatalf("last role=%q want user", got)
	}
	clean := cleanImagePrompt(lastUserContent(o.Messages))
	if !shouldUseChatImageRoute(o.Model, clean, o.Attachments) {
		t.Fatalf("Anthropic/Claude Code request missed image route after conversion: %q", clean)
	}
	for _, forbidden := range []string{"system-reminder", "coding agent", "/mnt/data"} {
		if strings.Contains(clean, forbidden) {
			t.Fatalf("converted prompt still contains injected context %q: %q", forbidden, clean)
		}
	}
}

func TestChatImagesRejectFalseSuccess(t *testing.T) {
	s := &Server{}
	r := httptest.NewRequest("POST", "http://nas/v1/chat/completions", nil)
	for _, sources := range [][]string{nil, {"data:image/png;base64," + base64.StdEncoding.EncodeToString([]byte("not an image"))}, {"https://example.org/image.png"}, {"data:image/png"}} {
		if imgs, err := s.hostChatImages(r.Context(), r, sources, auth.AccountToken{}); err == nil || len(imgs) != 0 {
			t.Fatalf("false success: %v %v", imgs, err)
		}
	}
	ctx, cancel := context.WithCancel(r.Context())
	cancel()
	if _, err := s.hostChatImages(ctx, r, []string{"data:image/png;base64,AA=="}, auth.AccountToken{}); !errors.Is(err, context.Canceled) {
		t.Fatalf("cancellation lost: %v", err)
	}
}

func TestWriteChatCompletionTextNonStreamingUsage(t *testing.T) {
	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
	server := &Server{}
	server.writeChatCompletionText(rr, req, "gpt-5.6-sol", "![image](http://example/image.png)", false, true, 17)

	var out map[string]any
	if err := json.Unmarshal(rr.Body.Bytes(), &out); err != nil {
		t.Fatal(err)
	}
	usage := out["usage"].(map[string]any)
	if got := int64(usage["prompt_tokens"].(float64)); got != 17 {
		t.Fatalf("prompt_tokens=%d want 17", got)
	}
	choices := out["choices"].([]any)
	content := choices[0].(map[string]any)["message"].(map[string]any)["content"].(string)
	if !strings.Contains(content, "![image]") {
		t.Fatalf("image markdown missing: %q", content)
	}
}

func TestRequestContextEnded(t *testing.T) {
	req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
	if requestContextEnded(req, nil) {
		t.Fatal("live request was classified as ended")
	}
	ctx, cancel := context.WithCancel(req.Context())
	cancel()
	if !requestContextEnded(req.WithContext(ctx), nil) {
		t.Fatal("canceled request context was not detected")
	}
}

func TestChatImageRouteTimeouts(t *testing.T) {
	for _, tc := range []struct {
		seconds int
		total   time.Duration
		attempt time.Duration
	}{
		{seconds: 2, total: 5 * time.Second, attempt: 5 * time.Second},
		{seconds: 120, total: 2 * time.Minute, attempt: 2 * time.Minute},
		{seconds: 300, total: 5 * time.Minute, attempt: 3 * time.Minute},
		{seconds: 3600, total: 10 * time.Minute, attempt: 3 * time.Minute},
	} {
		total, attempt := chatImageRouteTimeouts(tc.seconds)
		if total != tc.total || attempt != tc.attempt {
			t.Fatalf("seconds=%d got (%s,%s), want (%s,%s)", tc.seconds, total, attempt, tc.total, tc.attempt)
		}
	}
}

func TestChatModelCatalogIsCompleteAndUnique(t *testing.T) {
	models := configuredModelSpecs(defaultModelMappings)
	if len(models) != 15 {
		t.Fatalf("chat model catalog has %d models, want 15", len(models))
	}
	seen := map[string]bool{}
	for _, model := range models {
		if seen[model.ID] {
			t.Fatalf("duplicate chat model %q", model.ID)
		}
		seen[model.ID] = true
	}
	for _, want := range []string{"auto", "gpt-image-2", "gpt-5.6-sol", "gpt-5.6-terra", "gpt-5.6-luna"} {
		if !seen[want] {
			t.Fatalf("chat model catalog missing %q", want)
		}
	}
}

func TestImageModelConnectivityProbeDoesNotStartGeneration(t *testing.T) {
	probes := []string{
		"Say OK in one word.", "hello", "test connection",
		// The label a client was shown, echoed back as the prompt. d7c9143 stopped
		// displaying "GPT Image 2" so the echo would be the API id, but the id was
		// never added here, so these still went to the generation path.
		"gpt-image-2", "GPT-Image-2", "gpt image 2",
		// Punctuation and case decoration.
		"Say OK.", "Hello!", "hi.", "PING", "test.",
		// Chinese probes: this is a Chinese-facing gateway and none of these were
		// recognised before.
		"你好", "你好。", "您好", "在吗", "测试", "测试连接", "连接测试", "请回复",
		"你好，请回复OK", "你是什么模型",
		// A bare token of nothing.
		"1",
	}
	for _, prompt := range probes {
		if !isImageModelConnectivityProbe("gpt-image-2", prompt) {
			t.Fatalf("probe not recognized: %q", prompt)
		}
	}

	// A real image request must never be swallowed as a probe, whether it carries
	// an explicit image verb or is a terse description.
	for _, prompt := range []string{
		"生成一张仙侠海报", "draw a mountain", "生成图片",
		"一只戴帽子的猫", "a red circle on white",
		"你好，画一只猫",
	} {
		if isImageModelConnectivityProbe("gpt-image-2", prompt) {
			t.Fatalf("real image prompt classified as probe: %q", prompt)
		}
	}
	if isImageModelConnectivityProbe("gpt-5.6-sol", "hello") {
		t.Fatal("ordinary model probe must not be treated as image-model probe")
	}
}

// A connectivity probe must come back as a normal completion. Anything else -
// a 400 from the image-only restrictions, or a 30-180 second generation - makes
// a healthy endpoint look unreachable to the client that sent it.
func TestImageModelProbeIsAnsweredLocally(t *testing.T) {
	// The identity policy answers questions such as 你是什么模型 before the image
	// route; turn it off so every case below exercises the probe path.
	t.Setenv("M365_PUBLIC_IDENTITY_POLICY", "")

	cases := []struct {
		name string
		body string
	}{
		{"model label echo", `{"model":"gpt-image-2","messages":[{"role":"user","content":"gpt-image-2"}]}`},
		{"chinese greeting", `{"model":"gpt-image-2","messages":[{"role":"user","content":"你好"}]}`},
		{"punctuated greeting", `{"model":"gpt-image-2","messages":[{"role":"user","content":"Hello!"}]}`},
		{"test connection", `{"model":"gpt-image-2","messages":[{"role":"user","content":"test connection"}]}`},
		// Some clients attach response_format to every request. The probe must be
		// answered, not rejected with "gpt-image-2 does not support
		// response_format" - which is what happened before the probe check was
		// moved above that restriction.
		{"with response_format", `{"model":"gpt-image-2","response_format":{"type":"text"},"messages":[{"role":"user","content":"test connection"}]}`},
		{"streamed probe", `{"model":"gpt-image-2","stream":true,"messages":[{"role":"user","content":"ping"}]}`},
		{"probe with system turn", `{"model":"gpt-image-2","messages":[{"role":"system","content":"You are a helpful assistant."},{"role":"user","content":"hi"}]}`},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			st := &settingsStore{path: filepath.Join(t.TempDir(), "settings.json"), v: defaultRuntimeSettings()}
			s := &Server{settings: st}
			r := httptest.NewRequest("POST", "/v1/chat/completions", strings.NewReader(tc.body))
			w := httptest.NewRecorder()
			s.openaiChat(w, r)
			if w.Code != http.StatusOK {
				t.Fatalf("status=%d body=%s", w.Code, w.Body.String())
			}
			if !strings.Contains(w.Body.String(), "OK") {
				t.Fatalf("probe was not answered with OK: %s", w.Body.String())
			}
		})
	}
}

func TestChatImageStreamingWrapperEmitsSSEForAuthenticatedRequest(t *testing.T) {
	// The wrapper must not commit a silent JSON response before the long image
	// generation finishes. This test uses the unauthenticated branch to verify
	// that auth errors retain normal HTTP semantics; the authenticated branch is
	// covered by the same startChatImageKeepalive SSE helper used in production.
	s := &Server{}
	r := httptest.NewRequest("POST", "/api/chatui/images?stream=true", nil)
	r.Header.Set("Accept", "text/event-stream")
	rr := httptest.NewRecorder()
	s.chatImageGen(rr, r)
	if rr.Code != http.StatusUnauthorized {
		t.Fatalf("unauthenticated streaming image request status=%d, want 401", rr.Code)
	}
}

func TestChatImageKeepaliveAndStreamingErrorStaySSECompatible(t *testing.T) {
	rr := httptest.NewRecorder()
	req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
	stop, ok := startChatImageKeepalive(rr, req)
	if !ok {
		t.Fatal("httptest recorder should support flushing")
	}
	if got := rr.Header().Get("X-Accel-Buffering"); got != "no" {
		t.Fatalf("X-Accel-Buffering=%q, want no", got)
	}
	stop()
	writeChatImageRouteError(rr, true, errors.New("no image returned"))
	body := rr.Body.String()
	for _, want := range []string{": image generation started", `"type":"image_generation_error"`, "data: [DONE]"} {
		if !strings.Contains(body, want) {
			t.Fatalf("SSE route response missing %q: %s", want, body)
		}
	}
}

func TestWriteChatCompletionTextStreamingUsageOption(t *testing.T) {
	for _, tc := range []struct {
		name      string
		sendUsage bool
		wantUsage bool
	}{
		{name: "disabled", sendUsage: false, wantUsage: false},
		{name: "enabled", sendUsage: true, wantUsage: true},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rr := httptest.NewRecorder()
			req := httptest.NewRequest("POST", "/v1/chat/completions", nil)
			server := &Server{}
			server.writeChatCompletionText(rr, req, "gpt-5.6-sol", "![image](http://example/image.png)", true, tc.sendUsage, 23)
			body := rr.Body.String()
			if !strings.Contains(body, "data: [DONE]") || !strings.Contains(body, `"finish_reason":"stop"`) {
				t.Fatalf("invalid SSE completion: %s", body)
			}
			if got := strings.Contains(body, `"usage":`); got != tc.wantUsage {
				t.Fatalf("usage present=%v want %v: %s", got, tc.wantUsage, body)
			}
		})
	}
}
